// Generated by Scripts/generate-presets.swift from Presets/presets.json. Do not edit.
//
// Add or change a preset in Presets/presets.json, then run:
//
//     swift Scripts/generate-presets.swift

extension SitePresets {
    static let all: [SitePreset] = [
        SitePreset(
            id: "google-workspace",
            title: "Google Workspace",
            detail: "Gmail, Calendar, Drive, Docs, Meet, Chat, Groups, Contacts, Admin",
            hosts: [
                PresetHost("mail.google.com"),
                PresetHost("calendar.google.com"),
                PresetHost("drive.google.com"),
                PresetHost("docs.google.com"),
                PresetHost("meet.google.com"),
                PresetHost("chat.google.com"),
                PresetHost("groups.google.com"),
                PresetHost("contacts.google.com"),
                PresetHost("admin.google.com")
            ]
        ),
        SitePreset(
            id: "productivity-ai",
            title: "Productivity & AI",
            detail: "Notion, Linear, Slack, Atlassian, Claude, ChatGPT",
            hosts: [
                PresetHost("notion.so"),
                PresetHost("*.notion.so", .wildcard),
                PresetHost("linear.app"),
                PresetHost("slack.com"),
                PresetHost("*.slack.com", .wildcard),
                PresetHost("*.atlassian.net", .wildcard),
                PresetHost("claude.ai"),
                PresetHost("chatgpt.com")
            ]
        )
    ]
}
