// Generated by Scripts/generate-tracking-parameters.swift from Presets/tracking-parameters.json.
// Do not edit.
//
// Add or change a parameter in Presets/tracking-parameters.json, then run:
//
//     swift Scripts/generate-tracking-parameters.swift

extension TrackingParameters {
    /// Removed from every URL.
    static let globalNames: Set<String> = [
        "__hsfp",
        "__hssc",
        "__hstc",
        "_hsenc",
        "_hsmi",
        "_ke",
        "_openstat",
        "dclid",
        "ef_id",
        "epik",
        "fb_action_ids",
        "fb_action_types",
        "fb_source",
        "fbclid",
        "gad_source",
        "gbraid",
        "gclid",
        "gclsrc",
        "igsh",
        "igshid",
        "irclickid",
        "mc_cid",
        "mc_eid",
        "mkt_tok",
        "ml_subscriber",
        "ml_subscriber_hash",
        "msclkid",
        "oly_anon_id",
        "oly_enc_id",
        "rb_clickid",
        "s_kwcid",
        "srsltid",
        "ttclid",
        "twclid",
        "vero_conv",
        "vero_id",
        "wbraid",
        "wickedid",
        "yclid",
        "ysclid",
    ]

    /// Removed from every URL when the parameter name starts with one of these.
    static let globalPrefixes: [String] = [
        "hsa_",
        "matomo_",
        "mtm_",
        "piwik_",
        "pk_",
        "utm_",
    ]

    /// Removed only on the given host and its subdomains.
    static let hostScopedNames: [String: Set<String>] = [
        "linkedin.com": ["originalsubdomain", "trackingid", "trk"],
        "open.spotify.com": ["nd", "si"],
        "twitter.com": ["ref_src", "ref_url", "s", "t"],
        "x.com": ["ref_src", "ref_url", "s", "t"],
        "youtu.be": ["si"],
        "youtube.com": ["pp", "si"],
    ]
}
